# Where things are (defaults; but I like being explicit)

url: http://ehiggs.github.io
title: Technical Notes
author: Ewan Higgs
simple_search: 
description:

root:        /
permalink: /:year/:month/:title/
source:      ./.
destination: ./public
plugins_dir: ./plugins
layouts_dir: ./_layouts
data_dir:    ./_data
collections: null

highlighter: pygments
markdown: redcarpet
redcarpet: 
    extensions: [tables]

plugins:
    - jekyll-gist
whitelist:
    - jekyll-gist
